### ISSUE TITLE
Features translation

### ISSUE THREAD

**Issue by Tortoise17** [antoine77340/video_feature_extractor#13]
Dear friend 

I have to ask questions:
1) Is it possible to translate the features values and scores to the classes as output json?
2) Is it possible to catch these features at or with timestamps?

Please guide and help if this is possible.

**Comment by antoine77340** [comment]
Hi!

I have implemented neither 1 nor 2 but I believe it should be quite straightforward to add these features to the code now.

Especially for 1, do you mean that you want the classifier label scores? if yes you can change the backbone and use one which outputs scores instead of features.

For 2: Because the features are densely extracted at a fixed fps, it should be also easy to get the timestamp for each feature.
